### ISSUE TITLE
Harrison to make balsamiq mock up

### ISSUE THREAD

**Issue by jambardev** [jambardev/JECH-The-Explorers#1]

**Comment by Harrisong5** [comment]
[travel wireframe.pdf](https://github.com/jambardev/JECH-The-Explorers/files/15148930/travel.wireframe.pdf)

**Comment by Harrisong5** [comment]
[travel wireframe 1.1.pdf](https://github.com/jambardev/JECH-The-Explorers/files/15149160/travel.wireframe.1.1.pdf)
